CREATE DATABASE IF NOT EXISTS library;


USE library;

DROP TABLE IF EXISTS Loan;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Clients;
DROP TABLE IF EXISTS Topic;
DROP TABLE IF EXISTS Publishing_house;
DROP TABLE IF EXISTS Author;


CREATE TABLE Author (
	idauthor INT NOT NULL AUTO_INCREMENT,
	NameAuthor VARCHAR(60) NOT NULL,
	PRIMARY KEY (idauthor)
) ENGINE=InnoDB;

CREATE TABLE Publishing_house (
	idpublishing INT NOT NULL AUTO_INCREMENT,
	Namepublishing VARCHAR(30) NOT NULL,
	Address VARCHAR (100) NOT NULL,
	Telephone VARCHAR (15) NOT NULL, 
 	PRIMARY KEY (idpublishing)
) ENGINE=InnoDB;

CREATE TABLE Topic (
	idTopic INT NOT NULL AUTO_INCREMENT,
	NameTopic VARCHAR(30) NOT NULL,
	PRIMARY KEY (idTopic)
) ENGINE=InnoDB;

CREATE TABLE Clients (
	idClient INT NOT NULL AUTO_INCREMENT,
	NameClients VARCHAR(60) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	Email VARCHAR(25) NULL DEFAULT 'Sin Correo',
	Telephone VARCHAR(15) NOT NULL,
	PRIMARY KEY (idClient)
) ENGINE=InnoDB;

CREATE TABLE Book (
	idBook INT NOT NULL AUTO_INCREMENT,
	ISBN VARCHAR(20) NOT NULL UNIQUE,
	Tittle VARCHAR(65) NOT NULL,
	NumberExemplars TINYINT NOT NULL,
	idauthor INT NOT NULL,
	idpublishing INT NOT NULL,
	idTopic INT NOT NULL,
	PRIMARY KEY (idBook),
	FOREIGN KEY (idauthor) REFERENCES Author (idauthor) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (idpublishing) REFERENCES Publishing_house (idpublishing) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (idTopic) REFERENCES Topic (idTopic) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Loan (
	idLoan INT NOT NULL AUTO_INCREMENT,
	DateLoan DATE NOT NULL,
	DateDeliver DATE NOT NULL,
	idClient INT NOT NULL,
	idBook INT NOT NULL,
	PRIMARY KEY (idLoan),
	FOREIGN KEY (idClient) REFERENCES Clients (idClient) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (idBook) REFERENCES Book (idBook) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

